- name: empty
  mua: 0.0
  mus: 0.0
  g: 0.0
  n: 1.0
- name: region1
  mua: 0.01
  mus: 1.0
  g: 0.9
  n: 1.37
- name: region2
  mua: 0.01
  mus: 1.0
  g: 0.9
  n: 1.37
- name: region3
  mua: 0.01
  mus: 1.0
  g: 0.9
  n: 1.37
